import {
  LayoutDashboard,
  Calendar,
  PenLine,
  BookOpen,
  GraduationCap,
  Newspaper,
  Archive,
  Images,
  ClipboardList,
  Paperclip,
  Users,
  Settings,
  Wallet,
  BarChart3,
  ListChecks,
} from 'lucide-react';

export const adminSections = [
  { key: 'overview', label: 'نظرة عامة', title: 'نظرة عامة', icon: LayoutDashboard },
  { key: 'events', label: 'الفعاليات', title: 'إدارة الفعاليات', icon: Calendar },
  { key: 'writers', label: 'الكتّاب', title: 'إدارة الكتّاب', icon: PenLine },
  { key: 'publications', label: 'الإصدارات', title: 'إدارة الإصدارات', icon: BookOpen },
  { key: 'workshops', label: 'الورش', title: 'إدارة الورش', icon: GraduationCap },
  { key: 'news', label: 'الأخبار', title: 'إدارة الأخبار', icon: Newspaper },
  { key: 'archive', label: 'الأرشيف', title: 'الأرشيف السنوي', icon: Archive },
  { key: 'gallery', label: 'معرض الصور', title: 'معرض الصور', icon: Images },
  { key: 'files', label: 'الملفات', title: 'إدارة الملفات', icon: Paperclip },
  { key: 'users', label: 'المستخدمون', title: 'إدارة المستخدمين', icon: Users },
  { key: 'registrations', label: 'التسجيلات', title: 'إدارة التسجيلات', icon: ClipboardList },
  { key: 'costs', label: 'التكاليف', title: 'إدارة التكاليف', icon: Wallet },
  { key: 'reports', label: 'التقرير الشامل', title: 'التقرير الشامل للنظام', icon: BarChart3 },
  { key: 'tasks', label: 'المهام', title: 'متابعة المهام', icon: ListChecks },
  { key: 'settings', label: 'الإعدادات', title: 'إعدادات اللوحة', icon: Settings },
];